<?php
    $_helper = $this->helper('WeltPixel\ThankYouPage\Helper\Data');
    $_order = $block->getLastOrder();
    $items = $_order->getAllVisibleItems();
?>
<div class="order-info" >
    <?php if ($_helper->enablePrintOrder()) : ?>
        <?php if ($block->getCanViewOrder() && $block->getCanPrintOrder()) :?>
            <div>
                <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getPrintUrl() ?>"><span><?= /* @escapeNotVerified */ __('Print Order') ?></span></a>
            </div>
        <?php endif;?>
    <?php endif;?>
    <?php if ($_helper->showCustomerInfo()): ?>
        <div class="customer-info">
            <h4>Información de cliente</h4>
            <div class="address-wrapper">
                <div class="shipping-address">
                    <h4>Dirección de Envió</h4>
                    <p>
                        <?php if ($_order->getShippingAddress()): ?>
                            <?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()) ?>
                        <?php else: ?><?= __('No shipping address') ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="billing-address">
                    <h4><?= /* @escapeNotVerified */ __('Billing Address') ?></h4>
                    <p><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()) ?></p>
                </div>
            </div>
            <div class="methods-wrapper">
                <div class="shipping-method">
                    <h4><?= /* @escapeNotVerified */ __('Shipping Method') ?></h4>
                    <p>
                        <?php if ($block->getShippingMethodTitle($_order)): ?>
                            <?= /* @escapeNotVerified */ $block->getShippingMethodTitle($_order) ?>
                        <?php else: ?>
                            <?= __('No shipping method') ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="payment-method">
                    <h4>Método de pago</h4>
                    <p><?= /* @escapeNotVerified */ $block->getPaymentMethodTitle($_order) ?></p>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($_helper->showProductInfo()): ?>
        <div class="product-grid">
            <div class="table-wrapper order-items">
                <table class="data table table-order-items" id="table-order-items" style="line-height: 15px;">
                    <thead>
                        <tr>
                            <th class="col image textalign-center"><?= /* @escapeNotVerified */ __('Image') ?></th>
                            <th class="col name textalign-center" style="width:45%"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                            <th class="col sku textalign-center"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                            <th class="col price textalign-center"><?= /* @escapeNotVerified */ __('Price') ?></th>
                            <th class="col qty textalign-center"><?= /* @escapeNotVerified */ __('Qty') ?></th>
                            <th class="col subtotal textalign-center"><?= /* @escapeNotVerified */ __('Subtotal') ?></th>
                        </tr>
                    </thead>
                    <tbody style="line-height: 15px;">
                        <?= $this->getChildHtml('order.items'); ?>
                    </tbody>
                    <tfoot>
                        <?= $this->getChildHtml('order.totals'); ?>
                    </tfoot>
                </table>
            </div>
        </div>
    <?php endif; ?>
</div>

<style>
    .product-item-photo img {
    display: block;
    width: 75px;
    height: 75px;
    }
    .product-image-wrapper{
        padding-bottom: 100% !important;

    }
    .product-image-container{
        min-width: 0;
    }
    .product-item-name {
        font-size: 1em;
        white-space: nowrap;
        overflow: visible;
        text-overflow: ellipsis;
        display: block;
    }
    .product-item-photo {
    min-height: 0;
    }
</style>