<style>
    .titulo {
	color: #2D5D89;
	font-weight: 700;
	text-align: center;
	margin: 10px 0;
    }
</style>
<div class="about-info cms-content">
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-10">
            <h2 class="text-center titulo">GARANTÍA</h2>
            <br>
            <br>
            <p class="text-justify">
                Nos esforzamos por ofrecer productos de alta calidad y para respaldar esto contamos con políticas de garantía diseñadas para proteger tu compra.
                <br>
                <br>
                A continuación se detallan nuestras políticas y procedimientos para hacer válida una garantía:
                <br>
                <br>
                <strong style="line-height: 35px;"> Garantía de Productos Nuevos:</strong>
                <br>
                Todos nuestros productos nuevos cuentan con una garantía de fábrica válida a partir de la fecha de compra. Los términos y condiciones específicos de la garantía pueden variar según el fabricante y el producto, así como también el tiempo de la garantía. Si tienes algún problema con un producto nuevo dentro del período de garantía, te recomendamos ponerte en contacto con el servicio de atención al cliente del fabricante para solicitar asistencia técnica o activar la garantía según sea necesario. Si tienes alguna duda o requieres asistencia en el proceso, comunícate con nosotros y con gusto te asesoraremos.<br><br>
                <strong style="line-height: 35px;">Exclusiones de la Garantía:</strong>
                <br>
                La garantía no cubre daños causados por accidentes, uso indebido, modificaciones no autorizadas, negligencia o cualquier otra causa que no esté relacionada con defectos de fabricación. Además, algunos productos pueden tener garantías específicas proporcionadas directamente por el fabricante, te recomendamos revisar la documentación y los términos de garantía proporcionados por el fabricante para obtener información detallada sobre las coberturas y exclusiones específicas de cada producto.<br><br>
                <strong style="line-height: 35px;">Proceso de Reclamación de Garantía:</strong>
                <br>
                Si necesitas hacer una reclamación de garantía, te pedimos que te pongas en contacto con nuestro servicio de atención al cliente lo antes posible. Proporcionaremos asistencia y orientación adicional sobre cómo proceder. Es posible que necesitemos información adicional, como la prueba de compra y detalles sobre el problema experimentado, para procesar tu reclamación de garantía de manera adecuada te pedimos que tengas a la mano estos documentos y detalles antes de comunicarte con nosotros.
                Haremos todo lo posible para resolver cualquier problema que puedas tener con tu compra.
                <br>
                <br>
                Haremos todo lo posible para resolver cualquier problema que puedas tener con tu compra.
            </p>  
        </div>
        <div class="col-6">
        </div>
    </div>    
</div>
<br>
<br>
<div class="row">
    <div class="col-1">
    </div>
    <div class="col-10">
        <form method="POST" action="<?= $block->escapeUrl($block->getFormAction()) ?>" enctype="multipart/form-data">            
            <div class="col-12 form-control"> 
                <label for="name">Nombre Completo o Razon Social<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="nombre" placeholder="tu nombre completo" required>
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Folio del pedido<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="folio" placeholder="Folio del pedido"  required> 
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Fecha del pedido<span style="color: red;">*</span></label> 
                <input class="form-control" type="date" id="name" name="fecha" placeholder="Fecha del pedido"  required> 
            </div>
            <div class="col-12 form-control"> 
                <label for="name">Correo electrónico<span style="color: red;">*</span></label> 
                <input class="form-control" type="text" id="name" name="correo" placeholder="Direccion de correo electronico valido" required> 
            </div>        
        
            <div class="col-12 form-control"> 
                <label for="name">Telefono<span style="color: red;">*</span></label> 
                <input class="form-control" type="number" id="name" name="telefono" placeholder="Numero de Telefono" required> 
            </div>        
            <div class="col-12  form-control"> 
                <label for="name">Motivo de solicitud de garantia<span style="color: red;">*</span></label> 
                <textarea class="form-control" type="textarea" rows="8" id="name" name="motivo" placeholder="Motivo de solicitud de garantia"  required></textarea>
            </div>
            <br>            
            <div class="col-12 text-center">
                <button class="btn btn-primary" type="submit" name="uploadBtn" value="Upload">Enviar Mensaje</button>
            </div>    
        </form>
    </div>
    <div class="col-6">
    </div>
</div>
