<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Note: This mark is a requirement of PayPal
 * @var \Magento\Paypal\Block\Express\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @see \Magento\Paypal\Block\Express\Form
 */
$url = $block->escapeUrl($block->getPaymentAcceptanceMarkHref());
?>
<!-- PayPal Logo -->

    <?php if ($block->getPaymentWhatIs()) {
        echo $block->escapeHtml(__($block->getPaymentWhatIs()));
    } else {
        // echo $block->escapeHtml(__('What is PayPal?'));
    } ?>
<?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
    'onclick',
    "window.open(
           '" . /* @noEscape */ $block->escapeJs($block->getPaymentAcceptanceMarkHref()) . "',
           'olcwhatispaypal',
           'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,' +
           'left=0, top=0, width=400, height=350'
       ); event.preventDefault();",
    'a.action.paypal.about'
) ?>
<!-- PayPal Logo -->
